name: "clinicalbert_baseline"

model:
  model_name: "emilyalsentzer/Bio_ClinicalBERT"
  num_labels: 2

wandb:
  enabled: true
  project: "Pretrain-Qwen3-8B-Pancreas-classification"
  run_name: "baseline-clinicalbert"

training:
  output_dir: "/data/scratch/qc25022/pancreas/experiments/baselines/clinicalbert"
  overwrite_output_dir: true
  epochs: 3
  batch_size: 16
  eval_batch_size: 16
  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_steps: 100
  gradient_accumulation_steps: 1
  fp16: false
  bf16: false
  logging_steps: 50
  eval_steps: 250
  save_steps: 500
  save_total_limit: 2
  dataloader_num_workers: 8

data:
  cutoff_months: 6
  data_dir: "/data/scratch/qc25022/pancreas/tokenised_data_pancreas_MEDS/cprd_upgi"
  vocab_filepath: "/data/scratch/qc25022/pancreas/tokenised_data_pancreas_MEDS/cprd_upgi/vocab.csv"
  labels_filepath: "/data/home/qc25022/cancer-extraction-pipeline/output/pancreas_MEDS/subject_information.csv"
  medical_lookup_filepath: "/data/home/qc25022/TextCancEHR2/src/resources/MedicalDictTranslation2.csv"
  lab_lookup_filepath: "/data/home/qc25022/TextCancEHR2/src/resources/LabLookUP.csv"
  region_lookup_filepath: "/data/home/qc25022/TextCancEHR2/src/resources/RegionLookUp.csv"
  time_lookup_filepath: "/data/home/qc25022/TextCancEHR2/src/resources/TimeLookUp.csv"
  max_length: 512
  handle_long_sequences: "truncate"
  sort_by_length: true
  data_type: "binned"

